repos:
-   repo: https://github.com/Praveen-0208/developer-cheatsheet
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json